TARGET_EXEC  := transaction-generator
LDFLAGS      := -lpthread
CPP_COMPILER := /opt/rh/gcc-toolset-11/root/usr/bin/g++
CPPFLAGS     := -fcoroutines -std=c++2a -pthread -gdwarf-2

include ../Common/Common.mk
